name: PowerShell Manual # You can add your own name for the pipeline here

# Trigger when committing to main branch
on:
  workflow_dispatch: # Allow manual triggering of the workflow
    inputs:
      artifactId:
        description: 'The artifact ID to deploy'
        required: true
      target:
        type: choice
        description: Select target environment
        default: dev
        options: 
        - dev
        - stage
        - live

jobs:
  # Deploy to Umbraco Cloud
  # ####
  # you can edit the variables noBuildAndRestore, skipVersionCheck and allowAnyTarget
  # use 0 for false and 1 for true
  cloud-deployment:
    name: "Deploy to Cloud"
    uses: ./.github/workflows/ps-cloud-deployment.yml
    with:
      artifactId: ${{ github.event.inputs.artifactId }}
      targetEnvironmentAlias: ${{ github.event.inputs.target }}
      noBuildAndRestore: 1
      skipVersionCheck: 1
      allowAnyTarget: 1
    secrets:
      projectId: ${{ secrets.PROJECT_ID }}
      umbracoCloudApiKey: ${{ secrets.UMBRACO_CLOUD_API_KEY }}
